"""Comprobación visual opcional con Playwright; la aplicación no lo requiere."""
import json
import tempfile
import threading
from http.server import ThreadingHTTPServer
from pathlib import Path

from playwright.sync_api import sync_playwright, expect
from test_facturas import CONFIG, two_lines
from motor import connect
from servidor import application


def main():
    with tempfile.TemporaryDirectory() as temporary:
        db = Path(temporary)/'visual.sqlite3'
        con = connect(db)
        with con:
            con.execute('INSERT INTO empresas VALUES (?,?)', (CONFIG['nit'], json.dumps(CONFIG)))
        con.close()
        server = ThreadingHTTPServer(('127.0.0.1', 0), application(db))
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                incomplete = browser.new_page()
                incomplete_errors = []
                incomplete.on('pageerror', lambda error: incomplete_errors.append(str(error)))
                incomplete.route('**/flujo.js', lambda route: route.fulfill(status=404, content_type='application/json', body='{}'))
                incomplete.goto(f'http://127.0.0.1:{server.server_port}')
                expect(incomplete.locator('#notice')).to_contain_text('Iniciar conversor.cmd')
                expect(incomplete.locator('#upload')).to_be_disabled()
                expect(incomplete.locator('#invoiceRows [data-open]')).to_have_count(0)
                assert not incomplete_errors, incomplete_errors
                incomplete.close()
                page = browser.new_page(viewport={'width':1440, 'height':1000}, device_scale_factor=1)
                errors = []
                page.on('pageerror', lambda error: errors.append(str(error)))
                page.goto(f'http://127.0.0.1:{server.server_port}')
                page.wait_for_function('window.gravimentesWorkflowReady === true')
                expect(page.locator('#company')).to_have_value(CONFIG['nit'])
                page.locator('#company').select_option(CONFIG['nit'])
                page.wait_for_function('!busy')
                page.on('dialog', lambda dialog: dialog.accept())
                xml = two_lines()
                upload = {'name':'facturas.xml', 'mimeType':'text/xml', 'buffer':xml}
                page.locator('#files').set_input_files(upload)
                expect(page.locator('#invoiceRows [data-open]')).to_have_count(1)
                expect(page.locator('#notice')).to_contain_text('1 facturas nuevas')
                page.locator('#month').fill('2000-01')
                expect(page.locator('#invoiceRows [data-open]')).to_have_count(0)
                page.locator('#spaceDashboard').click()
                expect(page.locator('#dashboardView')).to_be_visible()
                expect(page.locator('#dashboardStats .stat')).to_have_count(4)
                page.locator('#spaceAccounting').click()
                expect(page.locator('#month')).to_have_value('2000-01')
                page.locator('#clearMonth').click()
                expect(page.locator('#invoiceRows [data-open]')).to_have_count(1)
                page.locator('#toggleModules').click()
                expect(page.locator('#moduleNav')).not_to_be_visible()
                page.locator('#toggleModules').click()
                expect(page.locator('#moduleNav')).to_be_visible()
                page.locator('#files').set_input_files({'name':'renombrada.xml', 'mimeType':'text/xml', 'buffer':xml})
                expect(page.locator('#notice')).to_contain_text('1 documentos repetidos omitidos')
                expect(page.locator('#invoiceRows [data-open]')).to_have_count(1)
                page.screenshot(path=r'C:\Users\ronz8\AppData\Local\Temp\opencode\gravimentes-facturas.png', full_page=True)
                page.locator('#reviewIssues').click()
                expect(page.locator('#invoiceDialog')).to_be_visible()
                expect(page.locator('#reviewPosition')).to_have_text('Incidencia 1 de 1')
                expect(page.locator('.revision-summary')).to_contain_text('Asigna una cuenta')
                expect(page.locator('[data-account]')).to_have_count(2)
                page.locator('#supplierAccount').fill('519530')
                page.locator('#applySupplierAccount').click()
                expect(page.locator('[data-account="0"]')).to_have_value('519530')
                expect(page.locator('[data-account="1"]')).to_have_value('519530')
                page.locator('#rememberSupplierAccount').click()
                expect(page.locator('#supplierAccountStatus')).to_contain_text('Cuenta recordada')
                page.wait_for_function('!busy')
                page.locator('[data-account="0"]').fill('519515')
                page.locator('[data-account="1"]').fill('143515')
                page.locator('#saveAccounts').click()
                expect(page.locator('#saveStatus')).to_contain_text('Cuentas guardadas')
                expect(page.locator('#detailPreview')).to_contain_text('Cuadra')
                page.locator('#supplierAccount').fill('519599')
                page.locator('#applySupplierAccount').click()
                expect(page.locator('[data-account="1"]')).to_have_value('143515')
                page.locator('.adjustments > summary').click()
                page.locator('#manualCxp').fill('220599')
                expect(page.locator('#detailPreview')).to_contain_text('220599')
                page.locator('#saveAccounts').click()
                expect(page.locator('#saveStatus')).to_contain_text('Cuentas guardadas')
                page.locator('#closeInvoice').click()
                page.locator('details.advanced > summary').click()
                page.locator('#undoLast').click()
                expect(page.locator('#notice')).to_contain_text('Cambio deshecho')
                page.reload()
                expect(page.locator('#invoiceRows .badge')).to_have_text('Lista')
                page.locator('[data-open]').click()
                expect(page.locator('[data-account="0"]')).to_have_value('519515')
                expect(page.locator('[data-account="1"]')).to_have_value('143515')
                expect(page.locator('#manualCxp')).to_have_value('')
                page.screenshot(path=r'C:\Users\ronz8\AppData\Local\Temp\opencode\gravimentes-detalle.png', full_page=True)
                page.locator('#closeInvoice').click()
                expect(page.locator('#currentPreview')).to_contain_text('1 de 1 facturas listas')
                page.locator('#generateSelected').click()
                expect(page.locator('#invoiceDialog')).not_to_be_visible()
                expect(page.locator('#invoiceRows .badge')).to_have_text('Lista')
                expect(page.locator('#invoiceRows')).to_contain_text('Plano disponible en Historial')
                expect(page.locator('#downloads')).to_contain_text('1 facturas generadas')
                expect(page.locator('#currentPreview .batch-downloads')).to_contain_text('Último resultado guardado')
                with page.expect_download() as plan_download:
                    page.locator('#currentPreview .batch-downloads a[href$="/txt"]').click()
                assert plan_download.value.suggested_filename.endswith('.txt')
                page.reload()
                expect(page.locator('#currentPreview .batch-downloads a[href$="/txt"]')).to_be_visible()
                page.locator('details.advanced > summary').click()
                page.locator('#openTabular').click()
                expect(page.locator('#tabularDialog')).to_be_visible()
                expect(page.locator('#tabularContent')).to_contain_text('IVA 19%')
                page.locator('#tabularHolds').select_option('yes')
                expect(page.locator('#tabularCount')).to_have_text('0 de 1 facturas')
                expect(page.locator('#exportTabular')).to_be_disabled()
                page.locator('#tabularHolds').select_option('no')
                expect(page.locator('#tabularCount')).to_have_text('1 de 1 facturas')
                page.locator('#tabularMixed').select_option('yes')
                expect(page.locator('#tabularCount')).to_have_text('0 de 1 facturas')
                page.locator('#tabularMixed').select_option('no')
                page.locator('#tabularRegime').fill('REGIMEN-INEXISTENTE')
                expect(page.locator('#tabularCount')).to_have_text('0 de 1 facturas')
                page.locator('#tabularRegime').fill('')
                with page.expect_download() as download_info:
                    page.locator('#exportTabular').click()
                assert download_info.value.suggested_filename == 'Revision_facturas.xlsx'
                page.locator('#closeTabular').click()
                page.locator('#openLearning').click()
                expect(page.locator('#learningDialog')).to_be_visible()
                expect(page.locator('#learningMessage')).to_contain_text('2 ejemplos activos · 0 excluidos')
                page.locator('#learningSearch').fill('NINGUN-EJEMPLO')
                expect(page.locator('#learningPageInfo')).to_contain_text('0 ejemplos')
                page.locator('#learningSearch').fill('PAPEL')
                expect(page.locator('#learningExamples [data-learning-invoice]')).to_have_count(2)
                page.locator('#learningExamples [data-learning-invoice]').first.click()
                expect(page.locator('#learningMessage')).to_contain_text('1 ejemplos activos · 1 excluidos')
                page.wait_for_function('!busy')
                page.locator('#learningTitle').click()
                page.keyboard.press('Control+z')
                expect(page.locator('#learningMessage')).to_contain_text('2 ejemplos activos · 0 excluidos')
                page.wait_for_function('!busy')
                page.locator('#closeLearning').click()
                page.keyboard.press('Control+k')
                expect(page.locator('#searchDialog')).to_be_visible()
                page.locator('#closeSearch').click()
                page.locator('#toggleTheme').click()
                expect(page.locator('html')).to_have_attribute('data-theme', 'dark')
                page.locator('#toggleTheme').click()
                second_xml = xml.replace(b'PRUEBA100', b'PRUEBA101').replace(b'CUFE-SINTETICO-PRUEBA-100', b'CUFE-PROVEEDOR-101')
                page.locator('#files').set_input_files({'name':'segunda.xml', 'mimeType':'text/xml', 'buffer':second_xml})
                expect(page.locator('#invoiceRows [data-open]')).to_have_count(2)
                expect(page.locator('#currentPreview')).to_contain_text('1 de 1 facturas listas')
                page.locator('#month').fill('2000-01')
                expect(page.locator('#currentPreview')).to_contain_text('No hay facturas listas')
                page.locator('#clearMonth').click()
                page.locator('#invoiceRows tr').filter(has_text='PRUEBA101').locator('[data-open]').click()
                expect(page.locator('[data-account="0"]')).to_have_value('519530')
                expect(page.locator('[data-account="1"]')).to_have_value('519530')
                page.locator('#supplierAccount').fill('519599')
                page.locator('#rememberSupplierAccount').click()
                expect(page.locator('#supplierAccountStatus')).to_contain_text('Cuenta recordada')
                page.wait_for_function('!busy')
                page.locator('#closeInvoice').click()
                page.locator('#undoLast').click()
                expect(page.locator('#notice')).to_contain_text('Cambio deshecho')
                page.locator('#invoiceRows tr').filter(has_text='PRUEBA101').locator('[data-open]').click()
                expect(page.locator('#supplierAccount')).to_have_value('519530')
                expect(page.locator('[data-account="1"]')).to_have_value('519530')
                page.locator('#closeInvoice').click()
                page.set_viewport_size({'width':390, 'height':844})
                expect(page.locator('#moduleNav')).not_to_be_visible()
                page.locator('#toggleModules').click()
                expect(page.locator('#moduleNav')).to_be_visible()
                page.locator('#moduleNav [data-view="invoices"]').click()
                expect(page.locator('#moduleNav')).not_to_be_visible()
                assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Desbordamiento móvil'
                page.locator('[data-open]').first.click()
                expect(page.locator('#invoiceDialog')).to_be_visible()
                assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Detalle desborda en móvil'
                assert not errors, errors
                browser.close()
                print('UI OK: carga, deduplicacion, detalle, cuentas persistentes, plano y movil. Sin errores JS.')
        finally:
            server.shutdown()
            server.server_close()
            thread.join()


if __name__ == '__main__':
    main()
